### ISSUE TITLE
config.Merge overwrites file options with defaults if cli args have not been provided

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/runner#24]
## Description

I run the binary without providing any arguments and uses a custom config file `./.benchttp.yml`.
My custom config:

```yml
request:
  method: GET
  url: http://localhost:9999?delay=10ms
  queryParams:
    fib: 5
  timeout: 2s

runnerOptions:
  requests: 9999
  concurrency: 99
  globalTimeout: 2s
```

As I provided all options, I expect `config.Merge` to overwrite the default with everything written here. However by adding some logs inside `makeRunnerConfig`, this is what I get:

```json
file {
  "Request": {
    "Method": "GET",
    "URL": {
      "Scheme": "http",
      "Opaque": "",
      "User": null,
      "Host": "localhost:9999",
      "Path": "",
      "RawPath": "",
      "ForceQuery": false,
      "RawQuery": "delay=10ms\u0026fib=5",
      "Fragment": "",
      "RawFragment": ""
    },
    "Timeout": 2000000000
  },
  "RunnerOptions": {
    "Requests": 9999,
    "Concurrency": 99,
    "GlobalTimeout": 2000000000
  }
}
cli {
  "Request": {
    "Method": "GET",
    "URL": {
      "Scheme": "",
      "Opaque": "",
      "User": null,
      "Host": "",
      "Path": "",
      "RawPath": "",
      "ForceQuery": false,
      "RawQuery": "",
      "Fragment": "",
      "RawFragment": ""
    },
    "Timeout": 10000000000 <- defaulted by config.Default(), expected zero value
  },
  "RunnerOptions": {
    "Requests": 0,
    "Concurrency": 1, <- defaulted by config.Default(), expected zero value
    "GlobalTimeout": 30000000000 <- defaulted by config.Default(), expected zero value
  }
}
merged {
  "Request": {
    "Method": "GET",
    "URL": {
      "Scheme": "http",
      "Opaque": "",
      "User": null,
      "Host": "localhost:9999",
      "Path": "",
      "RawPath": "",
      "ForceQuery": false,
      "RawQuery": "delay=10ms\u0026fib=5",
      "Fragment": "",
      "RawFragment": ""
    },
    "Timeout": 10000000000 <- wrongly overwritten, expected config file to not be overwritten
  },
  "RunnerOptions": {
    "Requests": 9999,
    "Concurrency": 1, <- wrongly overwritten, expected config file to not be overwritten
    "GlobalTimeout": 30000000000 <- wrongly overwritten, expected config file to not be overwritten
  }
}
```

## Suggestions

I suspect the problem lies in the steps the merge follows:
- read flags, default to zero-values if not given
- call `config.New` with flag-parsed values, internally `MergeDefault` overwrites the zero-values, the cli _has provided_ values
- call `config.Parse` to get the config file values, works as expected
- call `config.Merge` which overwrite file's values by cli's ones, but the cli one has been "corrupted" already

I have no immediate solution to suggest as I did not think enough about that. But I suspect an incremental build of the config would be easier to tackle when compare to handling a merge where so many null values can come from many different places (args, file and default).

Thinking is required ! 
For now I'll just pass args from the cli to short circuit the defaulting behavior.

**Comment by GregoryAlbouy** [comment]
This is due to the behaviour of `config.New`, that merges the created config with `config.Default()`.

This is indeed wrong, it should just return the created config.
